# Generated by Django 5.2 on 2025-04-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='reorder_point',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
