# Generated by Django 5.2 on 2025-05-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
