# Generated by Django 5.2 on 2025-05-07 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_supply_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='supply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.supply'),
        ),
    ]
